-- Generated by SQLcl REST Data Services 19.1.0.0
-- Exported REST Definitions from ORDS Schema Version 20.3.0.r3011819
-- Schema: TAYRA_APP   Date: Wed Mar 10 22:16:55 CET 2021
--
BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => user,
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'tayra',
      p_auto_rest_auth      => FALSE);    

  ORDS.DEFINE_MODULE(
      p_module_name    => 'upload',
      p_base_path      => '/api/test/',
      p_items_per_page =>  25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'upload',
      p_pattern        => 'results',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'upload',
      p_pattern        => 'results',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'Declare
  v_test_id number := 0;
Begin
  INSERT INTO uta_test_run (test_run_start_date,  test_run_result_xml, TEST_RUN_GROUP_ID, TEST_TITLE)
        VALUES (sysdate,  :body, :test_group_id, :test_title )
        RETURN id
        INTO v_test_id;

  uta_run_api.check_tests (v_test_id);

  :status := 201;
  logger.log(''v_test_id: ''||v_test_id, ''http://localhost:8080/ords/tayra/api/test/results'');  
  logger.log(''test_group_id: ''||:test_group_id, ''http://localhost:8080/ords/tayra/api/test/results'');  
  apex_json.open_object;
    apex_json.write(''success'', true);   
  apex_json.close_object;
End;'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'upload',
      p_pattern            => 'results',
      p_method             => 'POST',
      p_name               => 'test_group_id',
      p_bind_variable_name => 'test_group_id',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => 'Id unter der die Tests zusammengefasst werden');      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'upload',
      p_pattern            => 'results',
      p_method             => 'POST',
      p_name               => 'test_title',
      p_bind_variable_name => 'test_title',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => 'Bezeichnung des Testuploads');      


  COMMIT; 
END;
