  create table uta_test_suite 
   (	uta_test_run_id number, 
	id number generated by default on null as identity minvalue 1 maxvalue 9999999999999999999999999999 increment by 1 start with 1 cache 20 noorder  nocycle  nokeep  noscale  not null enable, 
	package_path varchar2(100 char), 
	testsuite_name varchar2(255 char), 
	testsuite_id number, 
	total_tests number, 
	disabled_tests number, 
	errored_tests number, 
	failed_tests number, 
	duration_sec varchar2(20 char), 
	system_out varchar2(4000 char), 
	system_err varchar2(4000 char), 
	tsu_id number
   ) ;