  create table uta_test_run 
   (	id number generated by default on null as identity minvalue 1 maxvalue 9999999999999999999999999999 increment by 1 start with 1 cache 20 noorder  nocycle  nokeep  noscale  not null enable, 
	test_run_start_date date, 
	test_run_end_date date, 
	test_run_result_xml clob, 
	total_tests number, 
	disabled_tests number, 
	errored_tests number, 
	failed_tests number, 
	duration_sec varchar2(20 char), 
	test_run_group_id number, 
	test_title varchar2(100 char)
   ) ;