  create table uta_test_case 
   (	uta_test_suite_id number, 
	id number generated by default on null as identity minvalue 1 maxvalue 9999999999999999999999999999 increment by 1 start with 1 cache 20 noorder  nocycle  nokeep  noscale  not null enable, 
	testcase_path varchar2(255 char), 
	testcase_name varchar2(255 char), 
	test_status varchar2(20 char), 
	assertions number, 
	duration_sec varchar2(20 char), 
	executed_on date, 
	error_statement varchar2(4000 char), 
	failure_statement varchar2(4000 char), 
	system_out varchar2(4000 char), 
	system_err varchar2(4000 char)
   ) ;